### ISSUE TITLE
Is it correct for def _dist_matmul?

### ISSUE THREAD

**Issue by ruilialice** [mil-tokyo/hyperbolic_nn_plusplus#1]
I am not sure about this, but it seems that the function def _dist_matmul in line [938](https://github.com/mil-tokyo/hyperbolic_nn_plusplus/blob/main/geoopt_plusplus/manifolds/stereographic/math.py#L938) of hyperbolic_nn_plusplus/geoopt_plusplus/manifolds/stereographic/math.py is not correct.

According to your paper, formula 13 on page 13 defines the MÖBIUS ADDITION, but it seems that the code misses the second part of the numerator.

**Comment by nhamanasu** [comment]
Thank you for your comment.

I checked the paper and my implementation, and still think they're both right. In order to compute a distance between two points, you should see Eq. 19 and 20, because Eq. 13 is about the (gyro)vector addition itself, while we need the norm when computing the distance. If you have any other question, please feel free to ask me.
